// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FlNWOS3Dwu3_BCqEp7fk5QsiwDGd2sI',
    appId: '1:315454762356:web:cc8be4beada9f08e575021',
    messagingSenderId: '315454762356',
    projectId: 'sketelonproject',
    authDomain: 'sketelonproject.firebaseapp.com',
    storageBucket: 'sketelonproject.appspot.com',
    measurementId: 'G-4DXPKEBP5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeZP4AD1lXOZrozYflUEY6UnRiVmZOicM',
    appId: '1:315454762356:android:5e4106aafb14727f575021',
    messagingSenderId: '315454762356',
    projectId: 'sketelonproject',
    storageBucket: 'sketelonproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBde1A0MdR1Fimsh4diAQvwDV6m3ruJAtg',
    appId: '1:315454762356:ios:d1a8822e81ceca43575021',
    messagingSenderId: '315454762356',
    projectId: 'sketelonproject',
    storageBucket: 'sketelonproject.appspot.com',
    iosClientId:
        '315454762356-ju2n0h32g0etnv8ie891tb58ag13pgso.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSkeleton',
  );
}
