import 'package:flutter/material.dart';

final ThemeData myTheme = ThemeData(
  primarySwatch: Colors.purple,
  brightness: Brightness.light,
  primaryColor: Color(0xff9c27b0),
  primaryColorLight: Color(0xffe1bee7),
  primaryColorDark: Color(0xff7b1fa2),
  canvasColor: Color(0xfffafafa),
  scaffoldBackgroundColor: Color(0xfffafafa),
  bottomAppBarColor: Color(0xffffffff),
  cardColor: Color(0xffffffff),
  dividerColor: Color(0x1f000000),
  highlightColor: Color(0x66bcbcbc),
  splashColor: Color(0x66c8c8c8),
  selectedRowColor: Color(0xfff5f5f5),
  unselectedWidgetColor: Color(0x8a000000),
  disabledColor: Color(0x61000000),
  toggleableActiveColor: Color(0xff8e24aa),
  secondaryHeaderColor: Color(0xfff3e5f5),
  backgroundColor: Color(0xffce93d8),
  dialogBackgroundColor: Color(0xffffffff),
  indicatorColor: Color(0xff9c27b0),
  hintColor: Color(0x8a000000),
  errorColor: Color(0xffd32f2f),
);
